### PR TITLE
Fix dispatch hanging when load() is called twice with the same key

### LINKED ISSUE #14: DataLoader hangs on several load() with the same key
If caching is disabled (i.e. `DataLoaderOptions.newOptions().setCachingEnabled(false)`), if you issue several `load()` with the same key, the loader will eventually hang once `dispatch()` is called.

This is most likely due to the field `loaderQueue` (defined in `DataLoader` class), which is a `Map`. On duplicate keys, the previous value (a CompletableFuture) is lost, and the `future` will never complete.

If caching is enabled, the same problem can happen due to a **race condition**. If 2 threads try to `load()` the same key at the same time, if the key is not yet in the `futureCache`, both threads will add it to the `loaderQueue` map, and one of the `future`s will be lost.

### PR DESCRIPTION
**Pull request by lburja**
Fixes #14

### CODE REVIEW

**Comment by kaqqao** [comment]
Sorry for a blunt question... but won't this now create multiple futures for the same key, which will get resolved separately, negating the benefits of bulk loading?
Would this problem be better solved by making `loaderQueue` a `ConcurrentHashMap` and `loaderQueue.putIfAbsent(key, future);`? That would remove the need for `synchronized` as well (and the concurrent map syncs on a bucket, so it's theoretically even more performant).

**Comment by lburja** [comment]
Yes, it will create multiple futures for the same key, but what I understand from the documentation is that this is the expected behavior:

>         userDataLoader.load("A");
>         userDataLoader.load("B");
>         userDataLoader.load("A");
> 
>         userDataLoader.dispatch();
> 
>         // will result in keys to the batch loader with [ "A", "B", "A" ]

So it is expected that the batch loader function receives keys A, B, A and answers with values X, Y, X. Thus, a Map does not work ...

Moreover, the loaderQueue is already in a synchronized block, and already behaves like a ConcurrentHashMap. But there is a race condition (with caching enabled), since 2 threads can reach at the same time the synchronized block, and both will add their future to the map:

 ```
       if (loaderOptions.cachingEnabled()) {
            synchronized (futureCache) {
                if (futureCache.containsKey(cacheKey)) {
                    stats.incrementCacheHitCount();
                    return futureCache.get(cacheKey);
                }
            }
        }

>>>>>>>> If 2 threads reach this, and they handle the same key, one of the values will be lost

        CompletableFuture<V> future = new CompletableFuture<>();
        if (loaderOptions.batchingEnabled()) {
            synchronized (loaderQueue) {
                loaderQueue.put(key, future);
            }
        }
        ...

```

**Comment by bbakerman** [comment]
Actually I dont think

```
    userDataLoader.load("A");
    userDataLoader.load("B");
    userDataLoader.load("A");

    userDataLoader.dispatch();

    // will result in keys to the batch loader with [ "A", "B", "A" ]
```

is the expected result.  I think off hand that it should return `["A","B"]` in map like semantics.

I will double check with the Facebook reference implementation but at first recall it seems that is the way it should work.

**Comment by bbakerman** [comment]
And I am wrong.  As outlined in https://github.com/facebook/dataloader

It is as you say, that is it expected to put in promises for each `.load(k)` call.  But it should have map like sermantics when caching is enabled

**Pull request merged**
